package com.ahlquist.sms.jpa.service;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Query;

import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.cfg.Configuration;

import com.ahlquist.sms.jpa.dao.CourseDAO;
import com.ahlquist.sms.jpa.entitymodels.Course;
/*
 * This class provides the methods to be used in the main method.
 * All these methods are related to the Course class, and Course manipulation.
 * 
 */
public class CourseService implements CourseDAO {
	List<Course> courseList = new ArrayList<Course>();

	/*
	 * method retrieves the course table using HQL queries
	 */
	public List<Course> getAllCourses() {
		SessionFactory factory = new Configuration().configure().buildSessionFactory();
		Session session = factory.openSession();
		String hql = "FROM Course";
		Query query = session.createQuery(hql);
		@SuppressWarnings("unchecked")
		List<Course> results = query.getResultList();
		courseList = results;
		session.close();
		factory.close();
		return results;
		
	}
	/*
	 * method retrieves specific courses from the courselist
	 * generated by the getAllCourses() method.
	 */
	public Course getCourseById(int cId) {
		Course c = new Course();
		for (Course b : courseList) {
			if (b.getcId() == cId){
				c.setcId(b.getcId());
				c.setcInstructorName(b.getcInstructorName());
				c.setcName(b.getcName());
			}
		}
		return c;
	}
	/*
	 * Method displayed all the courses retrieved by the getAllCourses method.
	 */
	public void displayAllCourses() {
		System.out.println("Here is a list of all the courses!");
		System.out.printf("%-10s %-30s %-20s\n", "Course ID", "Instructor", "Course Name");
		for (Course b: courseList) {
			System.out.printf("%-10s %-30s %-20s\n", b.getcId(), b.getcInstructorName(), b.getcName());
			
		}
	}
}
